export {Home} from './Home/Home'
export {Register} from './Register/Register'
export {Login} from './Login/Login'
export {ForgotPassword} from './ForgotPassword/ForgotPassword'
export {ResetPassword} from './ResetPassword/ResetPassword'
export {EditUser} from './InfoPanel/EditUser'
export {MakeAppointment} from './Appointment/MakeAppointment'
export {EditProfile} from './InfoPanel/EditProfile'
export {ListUser} from './InfoPanel/ListUser'
export {ListAppointment} from './InfoPanel/ListAppointment'
export {EditAppointment} from './Appointment/EditAppointment'
export {Patient as PatientDashboard} from './Dashboard/Patient'
export {Patient} from './List/Patient' 
export {Plan} from './Plan/Plan'
export {Nutritionist as NutritionistDashboard} from './Dashboard/Nutritionist'